CREATE TABLE IF NOT EXISTS dre_schema.tcomm_seg (
    actul_dt          DATE                    ENCODE AZ64,
    clnt_id           CHARACTER VARYING(20)   ENCODE ZSTD,
    clnt_nm           CHARACTER VARYING(150)  ENCODE ZSTD,
    pln_id            CHARACTER VARYING(12)   ENCODE ZSTD,
    pln_nm            CHARACTER VARYING(160)  ENCODE ZSTD,
    plan_type         CHARACTER VARYING(6)    ENCODE ZSTD,
    prt_id            CHARACTER VARYING(18)   ENCODE ZSTD,
    emp_div_loc       CHARACTER VARYING(32)   ENCODE ZSTD,
    prt_status_cd     CHARACTER VARYING(4)    ENCODE ZSTD,
    prt_brth_dt       DATE                    ENCODE AZ64,
    empmt_dt          DATE                    ENCODE AZ64,
    fnd_id            CHARACTER VARYING(12)   ENCODE ZSTD,
    src_id            CHARACTER VARYING(8)    ENCODE ZSTD,
    mkt_val           NUMERIC(15,2)           ENCODE AZ64,
    naisc_cd          CHARACTER VARYING(16)   ENCODE ZSTD,
    industry_cd       CHARACTER VARYING(4)    ENCODE ZSTD,
    lst_12month_flg   CHARACTER VARYING(2)    ENCODE ZSTD,
    er_ee_flg_plan    CHARACTER VARYING(4)    ENCODE ZSTD,
    fund_type         CHARACTER VARYING(50)   ENCODE ZSTD,
    tot_eqity         NUMERIC(15,2)           ENCODE AZ64,
    tot_eqity_pc      NUMERIC(15,2)           ENCODE AZ64,
    industry_cd_seg   CHARACTER VARYING(100)  ENCODE ZSTD,
    age_gr_seg        CHARACTER VARYING(100)  ENCODE ZSTD,
    job_ten_cd_seg    CHARACTER VARYING(100)  ENCODE ZSTD,
    naics_der_seg     CHARACTER VARYING(100)  ENCODE ZSTD,
    client_sz_cd_seg  CHARACTER VARYING(100)  ENCODE ZSTD,
    equity_cd_seg     CHARACTER VARYING(100)  ENCODE ZSTD,
    balance_cd_seg    CHARACTER VARYING(100)  ENCODE ZSTD,
    age_gr_seg_vpex   CHARACTER VARYING(100)  ENCODE ZSTD,
    age_gr_seg_5yrs   CHARACTER VARYING(100)  ENCODE ZSTD,
    term_dt           DATE                    ENCODE AZ64
)
DISTSTYLE AUTO;